### ISSUE TITLE
required labels red stars are misplaced when the form is placed inside a scrollable container

### ISSUE THREAD

**Issue by gregorius90** [icebob/vue-form-generator#218]
See this fiddle for example (i forked it from somewhere else and just adapted the max-height and overflow style attribute of the div container of the form):
https://jsfiddle.net/3fg4o9dv/1/

This is due to the fact that the :after that renders the star is positioned absolute
![requiredstarmisplaced](https://cloud.githubusercontent.com/assets/8641439/26627368/8d4cc80c-45fa-11e7-9a91-17219d18cd8a.jpg)

**Comment by dflock** [comment]
Well, it seems like removing the `position: absolute;` line from the `formGenerator.css` fixes this:

```css
&.required {
  > label:after {
    content: "*";
    font-weight: normal;
    color: Red;
    /* position: absolute; */
    padding-left: 0.2em;
    font-size: 1em;
  }
}
```
@icebob:

However, I can't figure out how to test this locally? I make the change - and webpack dev will recompile - but the dev examples don't seem to include `vfg.css` - which doesn't get compiled by `npm run dev` anyway?

When I add this css file to the `index.html`: https://unpkg.com/vue-form-generator@2.0.0-beta7/dist/vfg.css, it loads it, but I think this change: https://github.com/icebob/vue-form-generator/commit/b5d58ac broke the css; this is a separate issue, but it looks like formGenerator line 359 needs to change from this:

```css
  fieldset.vue-form-generator {
```

to this:

```css
  .vue-form-generator {
```
